/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Data = IDL.Record({
  'weight' : IDL.Opt(IDL.Int),
  'height' : IDL.Opt(IDL.Int),
  'hobby' : IDL.Opt(IDL.Text),
  'dateOfBirth' : IDL.Text,
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'education' : IDL.Opt(IDL.Text),
  'mobileNumber' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'create' : IDL.Func([IDL.Text, Data], [Data], []),
  'createPersonalRecord' : IDL.Func([Data], [Data], []),
  'delete' : IDL.Func([IDL.Text], [], []),
  'deletePersonalRecord' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPersonalRecordByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Data)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllAdmin' : IDL.Func([], [IDL.Vec(Data)], ['query']),
  'readAdmin' : IDL.Func([IDL.Text], [Data], ['query']),
  'readPersonalRecord' : IDL.Func([], [IDL.Opt(Data)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'update' : IDL.Func([IDL.Text, Data], [Data], []),
  'updatePersonalRecord' : IDL.Func([Data], [Data], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Data = IDL.Record({
    'weight' : IDL.Opt(IDL.Int),
    'height' : IDL.Opt(IDL.Int),
    'hobby' : IDL.Opt(IDL.Text),
    'dateOfBirth' : IDL.Text,
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'education' : IDL.Opt(IDL.Text),
    'mobileNumber' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'create' : IDL.Func([IDL.Text, Data], [Data], []),
    'createPersonalRecord' : IDL.Func([Data], [Data], []),
    'delete' : IDL.Func([IDL.Text], [], []),
    'deletePersonalRecord' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPersonalRecordByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Data)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllAdmin' : IDL.Func([], [IDL.Vec(Data)], ['query']),
    'readAdmin' : IDL.Func([IDL.Text], [Data], ['query']),
    'readPersonalRecord' : IDL.Func([], [IDL.Opt(Data)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'update' : IDL.Func([IDL.Text, Data], [Data], []),
    'updatePersonalRecord' : IDL.Func([Data], [Data], []),
  });
};

export const init = ({ IDL }) => { return []; };